<a href="https://colab.research.google.com/github/SaiArjunSairamje/Python_Libraries/blob/main/(01)%20Numpy_1%20(Dataset%3A%20Airbnb's_NPS)%20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Personal Note**

**NumPy Syllabus for Data Analyst/Scientist:**
***

**(1) Introduction to NumPy**

*   **numpy.array()**: Create a NumPy array from a Python list or tuple.
*   **numpy.arange()**: Generate an array with evenly spaced values within a specified range.
*   **numpy.linspace()**: Generate an array with evenly spaced values over a specified interval.
*   **numpy.zeros()**: Create arrays filled with zeros of a specified shape.
*   **numpy.ones()**: Create arrays filled with ones of a specified shape.
*   **numpy.eye()**: Generate an identity matrix of a given size.
*   **numpy.random.rand()**: Generate arrays with random numbers from a uniform distribution.
*   **numpy.random.randn()**: Generate arrays with random numbers from a standard normal distribution.

**(2) NumPy Arrays and Operations**

*   **numpy.array()**: Create a NumPy array from a Python list or tuple.
*   **numpy.arange()**: Generate an array with evenly spaced values within a specified range.
*   **numpy.linspace()**: Generate an array with evenly spaced values over a specified interval.
*   **numpy.zeros()**: Create arrays filled with zeros of a specified shape.
*   **numpy.ones()**: Create arrays filled with ones of a specified shape.

**Attributes and Methods:**

*   **ndim**: Get the number of array dimensions.
*   **shape**: Get the dimensions of the array.
*   **dtype**: Get the data type of elements in the array.

**(3) Broadcasting and Vectorization**

*   **numpy.add()**: Element-wise addition of two arrays.
*   **numpy.subtract()**: Element-wise subtraction of two arrays.
*   **numpy.multiply()**: Element-wise multiplication of two arrays.
*   **numpy.divide()**: Element-wise division of two arrays.

**(4) Array Mathematics and Statistics**

*   **numpy.sum()**: Compute the sum of array elements.
*   **numpy.mean()**: Compute the arithmetic mean of array elements.
*   **numpy.median()**: Compute the median of array elements.
*   **numpy.var()**: Compute the variance of array elements.
*   **numpy.std()**: Compute the standard deviation of array elements.
*   **numpy.min()**: Find the minimum value in an array.
*   **numpy.max()**: Find the maximum value in an array.
*   **numpy.dot()**: Compute the dot product of two arrays.
*   **numpy.matmul()**: Compute the matrix multiplication of two arrays.
*   **numpy.linalg.inv()**: Compute the inverse of a square matrix.
*   **numpy.linalg.det()**: Compute the determinant of a square matrix.

In [ ]:
a = [1, 2, 3, 4]

In [ ]:
type(a)

list

In [ ]:
for i in a:
  print(i**2)

1
4
9
16


In [ ]:
b = [i**2 for i in a] #list comprehension

In [ ]:
print(b)

[1, 4, 9, 16]


In [ ]:
import numpy as np

In [ ]:
a

[1, 2, 3, 4]

In [ ]:
type(a)

list

In [ ]:
b = np.array(a)

In [ ]:
print(b)

[1 2 3 4]


In [ ]:
type(b)

numpy.ndarray

In [ ]:
type(a)

list

In [ ]:
list1 = [4, 4.5, "AJ"]

In [ ]:
a = range(10000000)

In [ ]:
%timeit [i**2 for i in a]

3.49 s ± 421 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
# numpy.array(): Create a NumPy array from a Python list or tuple.

n1 = np.array(a)

In [ ]:
type(n1)

numpy.ndarray

In [ ]:
#vectorization --> coming in upcoming lectures

In [ ]:
%timeit n1**2

27.3 ms ± 343 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
type(n1)

numpy.ndarray

In [ ]:
print(n1)

[      0       1       2 ... 9999997 9999998 9999999]


In [ ]:
n1.ndim

1

In [ ]:
n1.shape

(10000000,)

In [ ]:
a = [ [1,2,3], [4,5,6], [7,8,9] ]

In [ ]:
type(a)

list

In [ ]:
b = np.array(a)

In [ ]:
type(b)

numpy.ndarray

In [ ]:
b.ndim

2

In [ ]:
b.shape

(3, 3)

In [ ]:
np.arange(1,5)

array([1, 2, 3, 4])

In [ ]:
np.arange(1,5, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

AttributeError: ignored

In [ ]:
b = np.array([4,5,7,6])

In [ ]:
print(b)

[4 5 7 6]


In [ ]:
type(b)

numpy.ndarray

In [ ]:
b = np.array([1, 2, 3, 4.0])
print(b)

[1. 2. 3. 4.]


In [ ]:
b = np.array([1,2,3,"AJ"])
print(b)

['1' '2' '3' 'AJ']


In [ ]:
np.array([1,2,3,4], dtype = "float")

array([1., 2., 3., 4.])

In [ ]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [ ]:
np.array(["AJ", "Naveen", "Sai", "Vinod"], dtype = "float")

ValueError: ignored

In [ ]:
a = np.array([1,2,3,4.0])

In [ ]:
print(a)

[1. 2. 3. 4.]


In [ ]:
a.dtype

dtype('float64')

In [ ]:
a = np.arange(12)

In [ ]:
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
type(a)

numpy.ndarray

In [ ]:
a[0]

0

In [ ]:
a[3]

3

In [ ]:
a[-1]

11

In [ ]:
a[:5]

array([0, 1, 2, 3, 4])

In [ ]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
print(a[-5:-1])

[6 7 8 9]


In [ ]:
a = np.arange(1,11)

In [ ]:
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
b = a < 6

In [ ]:
print(b)

[ True  True  True  True  True False False False False False]


In [ ]:
#masking
print(a[a < 6])

[1 2 3 4 5]


In [ ]:
a[[ True , True , True,  True , True, False ,False, False ,False, False]]

array([1, 2, 3, 4, 5])

In [ ]:
print(a[a>4])

[ 5  6  7  8  9 10]


In [ ]:
print(a[ a%2 == 0])

[ 2  4  6  8 10]


In [ ]:
#multi indexing in numpy

In [ ]:
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
a[6]

7

In [ ]:
a[8]

9

In [ ]:
print(a[[6,8]])

[7 9]


In [ ]:
print(a[[2,6,5]])

[3 7 6]


In [ ]:
b = a[[2,6,5]]

In [ ]:
type(b)

numpy.ndarray

In [ ]:
#Solving the NPS problem

In [ ]:
score = np.loadtxt("survey.txt", dtype = "int")

In [ ]:
type(score)

numpy.ndarray

In [ ]:
score[2]

5

In [ ]:
score[:5]

array([ 7, 10,  5,  9,  9])

In [ ]:
score[-1]

10

In [ ]:
score.shape

(1167,)

In [ ]:
score.ndim

1

In [ ]:
detractors = score[ score < 7]

In [ ]:
print(detractors)

[5 4 4 5 1 5 5 1 4 5 4 4 4 5 1 4 1 4 1 5 5 1 1 4 1 5 4 1 1 4 1 5 1 4 4 1 1
 1 1 1 1 1 4 1 1 5 5 5 4 4 1 4 1 4 1 5 1 1 5 4 4 4 4 1 4 5 4 4 1 1 5 5 1 5
 1 5 5 4 5 4 1 1 1 1 4 1 4 4 5 4 1 1 1 1 5 4 5 5 4 1 5 1 4 4 1 1 1 4 4 5 5
 4 5 5 5 1 4 1 5 5 1 5 1 1 5 5 4 4 1 4 4 4 1 1 4 4 4 5 5 1 1 4 1 4 1 4 1 4
 1 4 1 5 4 4 5 1 4 5 5 5 1 5 4 1 1 5 5 5 4 5 4 4 1 4 4 4 4 5 1 5 5 1 4 4 5
 1 1 4 5 5 5 1 4 5 5 4 1 5 5 5 1 1 5 5 1 1 1 4 5 5 4 4 4 5 1 4 1 4 5 4 5 5
 1 5 1 5 5 1 4 5 5 4 1 5 1 4 1 4 1 1 1 1 1 1 4 1 5 4 5 1 5 1 5 4 4 4 4 5 5
 1 4 1 5 5 1 4 1 1 4 4 4 4 1 4 1 1 4 1 5 4 1 1 5 4 5 4 4 4 1 5 5 1 4 5 4 4
 4 1 4 1 4 4 4 5 1 1 1 4 5 5 1 5 4 5 5 4 1 1 5 5 5 1 4 5 4 5 5 5 1 4 1 5]


In [ ]:
detractors.shape

(332,)

In [ ]:
num_detractors = len(detractors)

In [ ]:
print(num_detractors)

332


In [ ]:
score.min()

1

In [ ]:
score.max()

10

In [ ]:
promoters = score[ score > 8]

In [ ]:
num_promoters = len(promoters)

In [ ]:
print(num_promoters)

609


In [ ]:
total_users = len(score)
print(total_users)

1167


In [ ]:
percent_promoters = num_promoters/total_users

percent_detractors = num_detractors/total_users

In [ ]:
nps = (percent_promoters - percent_detractors)*100

In [ ]:
print(nps)

23.73607540702657


In [ ]:
#HW - to try to have the answer only till 2 decimal places